CREATE DATABASE IF NOT EXISTS `woop`
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS `woop`.`settings` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `type` ENUM('BOOLEAN', 'NUMBER', 'FLOAT', 'STRING', 'OBJECT') NOT NULL,
  `value` TEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `settings_name_UNIQUE` (`name` ASC)
) ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `woop`.`user` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) NOT NULL,
  `status` VARCHAR (7) NOT NULL DEFAULT 'VALID',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;


INSERT INTO `woop`.`settings` (`name`, `type`, `value`) VALUES
('LOG_BODY_BLACKLIST', 'OBJECT', '[\'password\']'),
('CRON_EVERY_SECOND', 'STRING', '* * * * * *');

