swagger: '2.0'
info:
  version: 1.0.0
  title: Woop Test"
  description: |
    Teste para Desenvolvedor(a) Backend do Woop Sicredi

    Produção: api.wooptest.com

    Homologação: api.homolog.wooptest.com

schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  "/session":
    post:
      summary: Cria uma nova sessão.
      parameters:
      - in: "body"
        name: "body"
      responses:
        200:
          description: Resultado
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: sempre true em caso de sucesso
              data:
                type: object
                properties:
                  session_id:
                    type: string
                    example: "3909"

  "/session/{session_id}":
    get:
      summary: Retorna dados da sessão.
      responses:
        200:
          description: Array com todos usuários em forma de objeto
          parameters:
          - name: "session_id"
            in: "path"
            description: "ID da sessão"
            required: true
            type: "integer"
          schema:
            type: object
            properties:
              success:
                type: boolean
                description: sempre true em caso de sucesso
              data:
                type: object
                properties:
                  session_id:
                    type: string
                    required: true
                    example: "3909"

  "/session/{session_id}/vote":
    post:
      summary: Lista todos os usuários.
      parameters:
      - name: "session_id"
        in: "path"
        description: "ID da sessão"
        required: true
        type: "integer"
      - in: "body"
        name: "body"
        required: true
        schema:
          type: object
          properties:
            session_id:
              type: string
              required: true
              example: "3909"
            option:
              type: string
              enum:
                - "YES"
                - "NO"
              required: true
              example: "YES"
      responses:
        204:
          description: Voto realizado com sucesso.
